# Generated by Django 5.0.6 on 2024-08-30 18:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminUsers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile_no', models.CharField(max_length=12)),
                ('nid', models.CharField(max_length=12, unique=True)),
                ('age', models.CharField(max_length=5)),
                ('religion', models.CharField(choices=[('ISLAM', 'Islam'), ('CHRISTIANITY', 'Christianity'), ('HINDUISM', 'Hinduism'), ('BUDDHISM', 'Buddhism'), ('JUDAISM', 'Judaism'), ('ATHEISM', 'Atheism'), ('OTHER', 'Other')], max_length=15)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='NormalUsers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile_no', models.CharField(max_length=12)),
                ('nid', models.CharField(max_length=12, unique=True)),
                ('age', models.CharField(max_length=5)),
                ('monthly_income', models.CharField(max_length=10)),
                ('religion', models.CharField(choices=[('ISLAM', 'Islam'), ('CHRISTIANITY', 'Christianity'), ('HINDUISM', 'Hinduism'), ('BUDDHISM', 'Buddhism'), ('JUDAISM', 'Judaism'), ('ATHEISM', 'Atheism'), ('OTHER', 'Other')], max_length=15)),
                ('account_type', models.CharField(choices=[('SAVINGS', 'Savings Account'), ('CHECKING', 'Checking Account'), ('BUSINESS', 'Business Account'), ('JOINT', 'Joint Account'), ('CURRENT', 'Current Account')], max_length=10)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
