# Generated by Django 5.0.6 on 2024-08-31 05:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='normalusers',
            old_name='user',
            new_name='normal_user',
        ),
    ]
