# Generated by Django 5.0.6 on 2024-08-31 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_rename_adminusers_manager_customer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='balance',
            field=models.CharField(blank=True, default='0', max_length=12, null=True),
        ),
    ]
