# Generated by Django 5.0.6 on 2024-08-31 18:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_customer_balance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='account_type',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='religion',
        ),
        migrations.RemoveField(
            model_name='manager',
            name='religion',
        ),
    ]
