# Generated by Django 5.0.6 on 2024-09-02 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_customer_account_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='account_no',
            field=models.CharField(editable=False, max_length=12, unique=True),
        ),
    ]
