# Generated by Django 5.1.1 on 2024-09-24 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_customer_account_type_customer_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='occupation',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
