# Generated by Django 5.0.6 on 2024-08-30 18:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='loan_approve',
        ),
    ]
