# Generated by Django 5.0.6 on 2024-08-30 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0002_remove_transaction_loan_approve'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.PositiveSmallIntegerField(choices=[('DEPOSIT', 'Deposit'), ('WITHDRAWAL', 'Withdrawal'), ('LOAN', 'Loan'), ('LOAN_PAID', 'Loan Paid')]),
        ),
    ]
